### ISSUE TITLE
Packge.json not found

### ISSUE THREAD

**Issue by Renato66** [marcosvcr84/challenge-backend#1]
error An unexpected error occurred: "/challenge-backend/package.json: Unexpected token v in JSON at position 0".

**Comment by marcosvcr84** [comment]
Because it was stored using GIT LFS as you can see here:

<img width="1254" alt="Screen Shot 2022-08-03 at 14 37 13" src="https://user-images.githubusercontent.com/19861661/182673268-2f00d65c-d25a-4da0-997e-eba0c61585c7.png">

Just download the file, the same for the other json files (transaction, account, category) used to populate the database.

Sorry about this, it's because the json files used to populate were a little bit large 
@Renato66

**Comment by marcosvcr84** [comment]
@Renato66

**Comment by marcosvcr84** [comment]
The other json files are inside prisma folder:

![Screen Shot 2022-08-03 at 14 40 36](https://user-images.githubusercontent.com/19861661/182673858-425d718b-16cc-4bef-b388-8b955c45a437.png)
